/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppProdutosRouteImport } from './routes/_app/produtos'
import { Route as AppPersonalizacaoRouteImport } from './routes/_app/personalizacao'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppConfiguracoesRouteImport } from './routes/_app/configuracoes'
import { Route as AppCategoriasRouteImport } from './routes/_app/categorias'
import { Route as authLoginRouteImport } from './routes/(auth)/login'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppProdutosRoute = AppProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => AppRoute,
} as any)
const AppPersonalizacaoRoute = AppPersonalizacaoRouteImport.update({
  id: '/personalizacao',
  path: '/personalizacao',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppConfiguracoesRoute = AppConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AppRoute,
} as any)
const AppCategoriasRoute = AppCategoriasRouteImport.update({
  id: '/categorias',
  path: '/categorias',
  getParentRoute: () => AppRoute,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof authLoginRoute
  '/categorias': typeof AppCategoriasRoute
  '/configuracoes': typeof AppConfiguracoesRoute
  '/dashboard': typeof AppDashboardRoute
  '/personalizacao': typeof AppPersonalizacaoRoute
  '/produtos': typeof AppProdutosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof authLoginRoute
  '/categorias': typeof AppCategoriasRoute
  '/configuracoes': typeof AppConfiguracoesRoute
  '/dashboard': typeof AppDashboardRoute
  '/personalizacao': typeof AppPersonalizacaoRoute
  '/produtos': typeof AppProdutosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/(auth)/login': typeof authLoginRoute
  '/_app/categorias': typeof AppCategoriasRoute
  '/_app/configuracoes': typeof AppConfiguracoesRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/personalizacao': typeof AppPersonalizacaoRoute
  '/_app/produtos': typeof AppProdutosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/categorias'
    | '/configuracoes'
    | '/dashboard'
    | '/personalizacao'
    | '/produtos'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/categorias'
    | '/configuracoes'
    | '/dashboard'
    | '/personalizacao'
    | '/produtos'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/(auth)/login'
    | '/_app/categorias'
    | '/_app/configuracoes'
    | '/_app/dashboard'
    | '/_app/personalizacao'
    | '/_app/produtos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  authLoginRoute: typeof authLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/produtos': {
      id: '/_app/produtos'
      path: '/produtos'
      fullPath: '/produtos'
      preLoaderRoute: typeof AppProdutosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/personalizacao': {
      id: '/_app/personalizacao'
      path: '/personalizacao'
      fullPath: '/personalizacao'
      preLoaderRoute: typeof AppPersonalizacaoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/configuracoes': {
      id: '/_app/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AppConfiguracoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/categorias': {
      id: '/_app/categorias'
      path: '/categorias'
      fullPath: '/categorias'
      preLoaderRoute: typeof AppCategoriasRouteImport
      parentRoute: typeof AppRoute
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppCategoriasRoute: typeof AppCategoriasRoute
  AppConfiguracoesRoute: typeof AppConfiguracoesRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppPersonalizacaoRoute: typeof AppPersonalizacaoRoute
  AppProdutosRoute: typeof AppProdutosRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCategoriasRoute: AppCategoriasRoute,
  AppConfiguracoesRoute: AppConfiguracoesRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppPersonalizacaoRoute: AppPersonalizacaoRoute,
  AppProdutosRoute: AppProdutosRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  authLoginRoute: authLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
